server:
  port: 8181
spring:
  devtools:
    add-properties: true
  application:
    name: "@project.artifactId@-@project.version@"
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    default-property-inclusion: NON_NULL
    locale: pt-BR
    time-zone: America/Sao_Paulo
  rabbitmq:
    connection-timeout: 5000
    request-timeout: 30000
    host: ${AMQP_URL:localhost}
    port: ${AMQP_PORT:5672}
    virtual-host: /spring_producer_vhost
    username: guest
    password: guest
    request:
      exchenge:
        producer: ex.producer.aula-spring
      routing-key:
        producer: rk.producer.aula-spring
      dead-letter:
        producer: dl.producer.aula-spring # Guardar as exceções de arquivos não lidos no projeto
      parking-lot:
        producer: pl.producer.aula-spring
logging:
  level:
    org:
      springframework: INFO
    com:
      example:
        spring: INFO
  file:
    name: ./logs/app.log
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    enabled: true
    disable-swagger-default-url: true
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: true
  packagesToScan: com.example.spring
  auto-tag-classes: false
management:
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui
info:
  app:
    name: "@project.artifactId@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
